version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
        restart: true
    networks:
      - internal
    container_name: app-store-test
  database:
    image: postgres:latest
    ports:
      - "8080:5432"
    container_name: db-store-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "storetest", "-U", "postgres"]
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
networks:
  internal:
    driver: bridge
